import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { runCmd } from './shell';
import { downloadFile } from './download';
import { LoggerService } from '../services/logger';

// ---------------------------------------------------------------------------
// Caddy Reverse Proxy Manager
// Provides HTTPS for *.odoo.local domains without port numbers
//
// Each project: https://project.odoo.local → http://localhost:port
// Caddy handles TLS with internal (self-signed) certificates
// ---------------------------------------------------------------------------

const CADDY_URL = 'https://caddyserver.com/api/download?os=windows&arch=amd64';
const CADDY_DIR_NAME = 'caddy';
const CADDYFILE_NAME = 'Caddyfile';

export interface CaddyProject {
  readonly domain: string;
  readonly port: string;
}

/**
 * Get Caddy directory (inside base dir).
 */
export function getCaddyDir(baseDir: string): string {
  return path.join(baseDir, CADDY_DIR_NAME);
}

/**
 * Get Caddy executable path.
 */
export function getCaddyExe(baseDir: string): string {
  return path.join(getCaddyDir(baseDir), 'caddy.exe');
}

/**
 * Check if Caddy is installed.
 */
export function isCaddyInstalled(baseDir: string): boolean {
  return fs.existsSync(getCaddyExe(baseDir));
}

/**
 * Download and install Caddy (single binary).
 */
export async function installCaddy(baseDir: string, logger: LoggerService): Promise<boolean> {
  const caddyDir = getCaddyDir(baseDir);
  const caddyExe = getCaddyExe(baseDir);

  if (fs.existsSync(caddyExe)) {
    logger.log('Caddy already installed.');
    return true;
  }

  fs.mkdirSync(caddyDir, { recursive: true });
  logger.log('Downloading Caddy server...');

  try {
    await downloadFile(CADDY_URL, caddyExe, logger, 'install_caddy');
    logger.log('Caddy installed!');

    // Trust Caddy's root CA (so browsers accept the self-signed certs)
    logger.log('  > Installing Caddy root CA certificate...');
    await runCmd(`"${caddyExe}" trust`, caddyDir);

    return true;
  } catch (e) {
    logger.log(`  > Caddy download failed: ${e}`);
    return false;
  }
}

/**
 * Generate Caddyfile from project list.
 */
export function generateCaddyfile(baseDir: string, projects: readonly CaddyProject[]): string {
  const caddyDir = getCaddyDir(baseDir);
  const caddyfilePath = path.join(caddyDir, CADDYFILE_NAME);

  let content = '# Auto-generated by Odoo 17 Installer\n';
  content += '# DO NOT EDIT - regenerated on each Start/Stop\n\n';

  for (const p of projects) {
    if (!p.domain || !p.port) continue;
    content += `${p.domain} {\n`;
    content += `  reverse_proxy localhost:${p.port}\n`;
    content += `  tls internal\n`;
    content += `}\n\n`;
  }

  fs.mkdirSync(caddyDir, { recursive: true });
  fs.writeFileSync(caddyfilePath, content, 'utf8');
  return caddyfilePath;
}

/**
 * Start or reload Caddy with current Caddyfile.
 */
export async function startCaddy(baseDir: string, logger: LoggerService): Promise<boolean> {
  const caddyExe = getCaddyExe(baseDir);
  const caddyDir = getCaddyDir(baseDir);
  const caddyfile = path.join(caddyDir, CADDYFILE_NAME);

  if (!fs.existsSync(caddyExe)) {
    logger.log('  > Caddy not installed, skipping HTTPS.');
    return false;
  }

  if (!fs.existsSync(caddyfile)) {
    logger.log('  > No Caddyfile found.');
    return false;
  }

  // Check if Caddy is already running - try reload first
  const { code: reloadCode } = await runCmd(`"${caddyExe}" reload --config "${caddyfile}"`, caddyDir);
  if (reloadCode === 0) {
    logger.log('  > Caddy reloaded with new config.');
    return true;
  }

  // Not running - start it
  logger.log('  > Starting Caddy server...');
  const { exec: execChild } = require('child_process');
  execChild(`"${caddyExe}" run --config "${caddyfile}"`, {
    cwd: caddyDir,
    windowsHide: true,
  });

  // Wait for Caddy to start
  await new Promise(resolve => setTimeout(resolve, 2000));
  logger.log('  > Caddy HTTPS proxy started.');
  return true;
}

/**
 * Stop Caddy server.
 */
export async function stopCaddy(baseDir: string, logger: LoggerService): Promise<void> {
  const caddyExe = getCaddyExe(baseDir);
  if (fs.existsSync(caddyExe)) {
    await runCmd(`"${caddyExe}" stop`);
    logger.log('  > Caddy stopped.');
  }
}
