import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { runCmd } from './shell';
import { downloadFile } from './download';
import { LoggerService } from '../services/logger';

// ---------------------------------------------------------------------------
// Caddy Reverse Proxy Manager
// Provides HTTPS for *.odoo.local domains without port numbers
//
// Each project: https://project.odoo.local → http://localhost:port
// Caddy handles TLS with internal (self-signed) certificates
// ---------------------------------------------------------------------------

// GitHub Releases: much faster CDN than caddyserver.com API
const CADDY_VERSION = '2.9.1';
const CADDY_URL = `https://github.com/caddyserver/caddy/releases/download/v${CADDY_VERSION}/caddy_${CADDY_VERSION}_windows_amd64.zip`;
const CADDY_DIR_NAME = 'caddy';
const CADDYFILE_NAME = 'Caddyfile';

export interface CaddyProject {
  readonly domain: string;
  readonly port: string;
}

/**
 * Get Caddy directory (inside base dir).
 */
export function getCaddyDir(baseDir: string): string {
  return path.join(baseDir, CADDY_DIR_NAME);
}

/**
 * Get Caddy executable path.
 */
export function getCaddyExe(baseDir: string): string {
  return path.join(getCaddyDir(baseDir), 'caddy.exe');
}

/**
 * Check if Caddy is installed.
 */
export function isCaddyInstalled(baseDir: string): boolean {
  return fs.existsSync(getCaddyExe(baseDir));
}

/**
 * Download and install Caddy (single binary).
 */
export async function installCaddy(baseDir: string, logger: LoggerService): Promise<boolean> {
  const caddyDir = getCaddyDir(baseDir);
  const caddyExe = getCaddyExe(baseDir);

  // Verify existing binary is valid (not corrupt/truncated)
  if (fs.existsSync(caddyExe)) {
    const size = fs.statSync(caddyExe).size;
    if (size > 10_000_000) { // Valid caddy binary is >10MB
      logger.log('Caddy already installed.');
      return true;
    }
    // Corrupt file — delete and re-download
    logger.log('Caddy binary appears corrupt, re-downloading...');
    fs.unlinkSync(caddyExe);
  }

  fs.mkdirSync(caddyDir, { recursive: true });
  logger.log('Downloading Caddy server...');

  try {
    // Download zip from GitHub Releases (fast CDN)
    const zipPath = path.join(caddyDir, 'caddy.zip');
    logger.log('  > Downloading from GitHub...');
    const { code } = await runCmd(`curl -L -o "${zipPath}" --connect-timeout 10 --max-time 300 "${CADDY_URL}"`);
    if (code !== 0 || !fs.existsSync(zipPath) || fs.statSync(zipPath).size < 1_000_000) {
      if (fs.existsSync(zipPath)) fs.unlinkSync(zipPath);
      throw new Error('Download failed');
    }
    // Extract caddy.exe from zip using PowerShell
    logger.log('  > Extracting...');
    await runCmd(`powershell -NoProfile -Command "Expand-Archive -Path '${zipPath}' -DestinationPath '${caddyDir}' -Force"`);
    // Cleanup zip
    if (fs.existsSync(zipPath)) fs.unlinkSync(zipPath);
    // Validate
    if (!fs.existsSync(caddyExe) || fs.statSync(caddyExe).size < 10_000_000) {
      throw new Error('Extract failed or binary corrupt');
    }
    logger.log('Caddy installed!');

    // Trust Caddy's root CA (so browsers accept the self-signed certs)
    logger.log('  > Installing Caddy root CA certificate...');
    await runCmd(`"${caddyExe}" trust`, caddyDir);

    return true;
  } catch (e) {
    logger.log(`  > Caddy download failed: ${e}`);
    return false;
  }
}

/**
 * Generate Caddyfile from project list.
 */
export function generateCaddyfile(baseDir: string, projects: readonly CaddyProject[]): string {
  const caddyDir = getCaddyDir(baseDir);
  const caddyfilePath = path.join(caddyDir, CADDYFILE_NAME);

  let content = '# Auto-generated by Odoo 17 Installer\n';
  content += '# DO NOT EDIT - regenerated on each Start/Stop\n\n';

  for (const p of projects) {
    if (!p.domain || !p.port) continue;
    content += `${p.domain} {\n`;
    content += `  reverse_proxy localhost:${p.port}\n`;
    content += `  tls internal\n`;
    content += `}\n\n`;
  }

  fs.mkdirSync(caddyDir, { recursive: true });
  fs.writeFileSync(caddyfilePath, content, 'utf8');
  return caddyfilePath;
}

/**
 * Start or reload Caddy with current Caddyfile.
 */
export async function startCaddy(baseDir: string, logger: LoggerService): Promise<boolean> {
  const caddyExe = getCaddyExe(baseDir);
  const caddyDir = getCaddyDir(baseDir);
  const caddyfile = path.join(caddyDir, CADDYFILE_NAME);

  if (!fs.existsSync(caddyExe)) {
    logger.log('  > Caddy not installed, skipping HTTPS.');
    return false;
  }

  if (!fs.existsSync(caddyfile)) {
    logger.log('  > No Caddyfile found.');
    return false;
  }

  // Check if Caddy is already running - try reload first
  const { code: reloadCode } = await runCmd(`"${caddyExe}" reload --config "${caddyfile}"`, caddyDir);
  if (reloadCode === 0) {
    logger.log('  > Caddy reloaded with new config.');
    return true;
  }

  // Not running - start it
  logger.log('  > Starting Caddy server...');
  const { exec: execChild } = require('child_process');
  execChild(`"${caddyExe}" run --config "${caddyfile}"`, {
    cwd: caddyDir,
    windowsHide: true,
  });

  // Wait for Caddy to start
  await new Promise(resolve => setTimeout(resolve, 2000));
  logger.log('  > Caddy HTTPS proxy started.');
  return true;
}

/**
 * Stop Caddy server.
 */
export async function stopCaddy(baseDir: string, logger: LoggerService): Promise<void> {
  const caddyExe = getCaddyExe(baseDir);
  if (fs.existsSync(caddyExe)) {
    await runCmd(`"${caddyExe}" stop`);
    logger.log('  > Caddy stopped.');
  }
}
